//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18047
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Link.EFAM.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Link.EFAM.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   값은 빈 문자열(&quot;&quot;)일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_EmptyString {
            get {
                return ResourceManager.GetString("Argument_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값은 null이거나 빈 문자열(&quot;&quot;)일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_NullOrEmptyString {
            get {
                return ResourceManager.GetString("Argument_NullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값은 빈 문자열(&quot;&quot;)이거나 공백만 포함할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_WhiteSpaceString {
            get {
                return ResourceManager.GetString("Argument_WhiteSpaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AD 계정이 만료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_ADAccountExpired {
            get {
                return ResourceManager.GetString("Error_ADAccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 키를 가진 항목이 이미 추가 되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_AlreadyAddedInCollection {
            get {
                return ResourceManager.GetString("Error_AlreadyAddedInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에 등록된 도메인 이름과 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_DomainNameMismatch {
            get {
                return ResourceManager.GetString("Error_DomainNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 파일이 이미 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Error_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; 파일을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   활성화된 사용자가 아닙니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_InactiveUser {
            get {
                return ResourceManager.GetString("Error_InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호를 잘못 입력하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 속성 값이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_InvalidProperty {
            get {
                return ResourceManager.GetString("Error_InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LDAP의 경로가 등록되어 있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_LDAPNotFound {
            get {
                return ResourceManager.GetString("Error_LDAPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지정한 인수가 유효한 값 범위를 벗어났습니다. 지정한 값은 {0} 보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_OutOfRangeParameter_Gt {
            get {
                return ResourceManager.GetString("Error_OutOfRangeParameter_Gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속성 값이 범위를 벗어났습니다. {0} 속성 값은 {1} 보다 커야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_OutOfRangeProperty_Gt {
            get {
                return ResourceManager.GetString("Error_OutOfRangeProperty_Gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속성 값이 범위를 벗어났습니다. {0} 속성 값은 {1} 보다 크거나 같아야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_OutOfRangeProperty_GtOrEq {
            get {
                return ResourceManager.GetString("Error_OutOfRangeProperty_GtOrEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 만료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_PasswordExpired {
            get {
                return ResourceManager.GetString("Error_PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차단된 IP 주소입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_RestrictedIPAddress {
            get {
                return ResourceManager.GetString("Error_RestrictedIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차단된 MAC 주소입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_RestrictedMACAddress {
            get {
                return ResourceManager.GetString("Error_RestrictedMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디가 등록되어 있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로 &quot;{0}&quot;에 대한 액세스가 거부되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnauthorizedAccess_Path {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Path", resourceCulture);
            }
        }
    }
}
